name: Generate i18n Files

on:
  push:
    paths:
      - 'src/**'
      - 'templates/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 运行生成脚本
        run: python generate-i18n.py

      - name: 提交生成的文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动生成多语言文件"
          file_pattern: "i18n/*.json"
          branch: main
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
