name: Generate i18n Files

on:
  push:
    paths:
      - 'src/**'
      - 'templates/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 关键：启用持久化凭证

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 运行生成脚本
        run: python generate-i18n.py

      - name: 提交生成的文件
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add i18n/*.json
          git commit -m "自动生成多语言文件"
          git push origin main
